[project]
name = "bookings"
authors = [
    { name = "Frank Nyarkoh", email = "frank.nyarkoh@hotmail.com" },
]
description = "App for managing hotel bookings"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # "frappe" is managed by bench; see [tool.bench.frappe-dependencies]
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<16.0.0"
